### ISSUE TITLE
Utilizing internals causes crashes between versions

### ISSUE THREAD

**Issue by Linguardium** [Cristelknight999/Cristel-Lib#16]
https://github.com/Cristelknight999/Cristel-Lib/blob/bf2e5c06caa9ad7c924efb7a121bef02e06e9b77/fabric-like/src/main/java/net/cristellib/fabriclike/CristelLibFabricLikePlatform.java#L8

impl packages are internal implementation and can change at any time, even between patch versions. Referencing impl details directly causes the mod (and any mod that relies on it) to be extremely fragile to version changes.

If using implementation classes directly, please properly mark the required version you are developing against in your fabric.mod.json file

**Comment by Eyorie** [comment]
https://mclo.gs/1a2Y2l8

Here is a latest log file for reference because I have the same problem too

**Comment by Deirel** [comment]
I have faced this error too

**Comment by Eyorie** [comment]
> I have faced this error too

Did you find a solution or fix?

**Comment by Cristelknight999** [comment]
Should be fixed in n the newest version

**Comment by codingmakesmyheadhurt** [comment]
definitely not fixed, I still run into errors on the most recent version.
